apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wize-comment-ingress
  namespace: wizeworks
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-brandonkorous
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.wize.works
      secretName: wizeworks-tls
  rules:
    - host: api.wize.works
      http:
        paths:
          - path: /comment/(.*)
            pathType: Prefix
            backend:
              service:
                name: wize-comment-service
                port:
                  number: 80